CREATE DATABASE IF NOT EXISTS systemJWT;
CREATE USER 'userJWT'@'%' IDENTIFIED BY 'ala#tola';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, FILE, INDEX, ALTER, CREATE TEMPORARY TABLES  ON *.* TO 'userJWT'@'%';